### ISSUE TITLE
Trouble installing XMPP libraries

### ISSUE THREAD

**Issue by jpakusch** [mitchtech/raspi_gtalk_robot#2]
Hello, really an interesting Project i like to realize myself!

I would be very glad if you could help me.

I have trouble installing the XMPP Library.

I do the following: 
sudo pip install RPi.GPIO xmpppy pydns

I get the following:

Downloading/unpacking xmpppy Could not find a version that satisfies the requirement xmpppy (from versions: 0.5.0rc1) Cleaning up... No distributions matching the version for xmpppy Storing debug log for failure in /root/.pip/pip.log 

Can anyone help me?

greetings, Jan

**Comment by molayac** [comment]
Try using:

> **sudo easy_install RPi.GPIO xmpppy pydns**

Regards,
Molayac

**Comment by jpakusch** [comment]
Thank you very much, that was new to me and it helped!
